name: Uplaod and download
on:
 push:
  branches:
    - master
jobs:
 uploadfile:
  runs-on: ubuntu-latest
  steps:
  - name: create a file
    run: mkdir myfiles
  - name: create a file in directory
    run: echo "Hello ALL" > myfiles/file1
  - name: upload the file to github
    uses: actions/upload-artifact@v4
    with:
      name: myfiles
      path: myfiles/file1
 downloadfile:
    runs-on: ubuntu-latest
    needs: uploadfile
    steps:
      - name: download the artifact from previous job
        uses: actions/download-artifact@v4
        with:
         name: myfiles
      - name: check if the file is on runner or not
        run: ls -ltr
